
export const TICKET_FIELDS = {
  ticket_number: "ticket_number",
  visitorId: "visitorId",
  car_model: "car_model",
  plate_number: "plate_number",
  vehicleInfo: "vehicleInfo",
  guestName: "guestName",
  status: "status",
  created_at: "created_at",
  updatedAt: "updatedAt",
  assignedWorker: "assignedWorker",
  assignedAt: "assignedAt",
  etaMinutes: "etaMinutes",
  requestedAt: "requestedAt",
  completedAt: "completedAt",
  cancelledAt: "cancelledAt",
  preAlertSent: "preAlertSent",
  ticket_url: "ticket_url",
};
